version: "3.9"

volumes:
  pgdata:

services:
  db:
    container_name: flask_db
    image: postgres:14.3-alpine3.15
    restart: always
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
